### ISSUE TITLE
Win machine fails on Maximum time exceeded timeout

### ISSUE THREAD

**Issue by cohoren** [QualiSystems/OpenStack-Shell#114]
1. have 2 app, one cirros second win
2. reserve

BIR:

the win machine fails on Maximum time exceeded 

Error: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
Traceback (most recent call last):
  File "C:\Program Files (x86)\QualiSystems\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Program Files (x86)\QualiSystems\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Windows\TEMP\b5a4646d-33b6-4d67-8a90-7520c1c620f0\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Windows\TEMP\b5a4646d-33b6-4d67-8a90-7520c1c620f0\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Windows\TEMP\b5a4646d-33b6-4d67-8a90-7520c1c620f0\Default Sandbox Setup.zip\sandbox_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Windows\TEMP\b5a4646d-33b6-4d67-8a90-7520c1c620f0\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 56, in execute
  File "C:\Windows\TEMP\b5a4646d-33b6-4d67-8a90-7520c1c620f0\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 222, in _run_async_power_on_refresh_ip_install
  File "C:\Windows\TEMP\b5a4646d-33b6-4d67-8a90-7520c1c620f0\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 228, in _validate_all_apps_deployed
Exception: Reservation is Active with Errors - CloudShellAPIError: Command execution failed with error: 'InstanceWaiterTimeoutException'.

Error description: Maximum time exceeded waiting                                         for Instance OpenStackAppWindows-02df3192

**Comment by yairbb** [comment]
@gabhijit-izel

**Comment by alexazarh** [comment]
We need to have the app deploy timeout as an attribute on the deployment model.
It should not be a user input by default.
Default value is 10 minutes

**Comment by TomerAdmon** [comment]
Name: App Deployment Timeout
Type: Numeric
default: 10
User input: No
Description: Timeout in minuets for the app deployment process.

**Comment by gabhijit-izel** [comment]
This will be completely on the Server Side right? There is no code required for this on the Shell, Right?

**Comment by alexazarh** [comment]
@gabhijit-izel No. It is 100% on the shell side. Why it should be on the server side since the waiter is implemented in the shell?

**Comment by TomerAdmon** [comment]
closing and opening this one: https://github.com/QualiSystems/OpenStack-Shell/issues/118
