### ISSUE TITLE
Connectivity Error: App connected to Moc

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#117]
STR:

1) Have an env with Un deployed App and MocL2.
2) Connect the Spp to Moc  with Port1.
3) Reserve the Env.

BIR:

The reservation failed with Active with Error. Actually the VM was deployed in OpenStack.

Attached the Log:

Error: Script runner exited with exit code: 1
Description: 2017-01-12 16:58:40,864 [INFO]: Setup.CloudShell_Sandbox_Setup setup_script - _prepare_connectivity Preparing connectivity for reservation 9804b849-b492-413e-97d6-a84f6c8b4d8a
2017-01-12 16:58:41,319 [INFO]: Setup.CloudShell_Sandbox_Setup setup_script - _deploy_apps_in_reservation Deploying apps for reservation . App names: OpenStackApp
2017-01-12 16:59:27,181 [INFO]: Setup.CloudShell_Sandbox_Setup setup_script - _try_exeucte_autoload Executing Autoload command on deployed app OpenStackApp-6ab28a13
2017-01-12 16:59:27,430 [INFO]: Setup.CloudShell_Sandbox_Setup setup_script - _connect_all_routes_in_reservation Executing connect routes for reservation 9804b849-b492-413e-97d6-a84f6c8b4d8a
2017-01-12 16:59:27,430 [DEBUG]: Setup.CloudShell_Sandbox_Setup setup_script - _connect_all_routes_in_reservation Connecting: MockL2/Chassis/Port1,OpenStackApp-6ab28a13
Traceback (most recent call last):
  File "C:\Work\QualiSystems\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\QualiSystems\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\yair.b\AppData\Local\Temp\d77cd57d-8f6e-44d2-847f-a73a89e07643\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Users\yair.b\AppData\Local\Temp\d77cd57d-8f6e-44d2-847f-a73a89e07643\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\yair.b\AppData\Local\Temp\d77cd57d-8f6e-44d2-847f-a73a89e07643\Default Sandbox Setup.zip\sandbox_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Users\yair.b\AppData\Local\Temp\d77cd57d-8f6e-44d2-847f-a73a89e07643\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 50, in execute
  File "C:\Users\yair.b\AppData\Local\Temp\d77cd57d-8f6e-44d2-847f-a73a89e07643\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 180, in _connect_all_routes_in_reservation
  File "C:\Work\QualiSystems\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1990, in ConnectRoutesInReservation
    return self.generateAPIRequest(OrderedDict([('method_name', 'ConnectRoutesInReservation'), ('reservationId', reservationId), ('endpoints', CommonAPIRequest.toContainer(endpoints)), ('mappingType', mappingType)]))
  File "C:\Work\QualiSystems\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 419, in generateAPIRequest
    raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 100: Endpoint Port1 is not a connectable resource

**Comment by TomerAdmon** [comment]
@yairbb - "Endpoint Port1 is not a connectable resource" - can you try change port1 model to be connectable?

**Comment by yairbb** [comment]
NA
