### ISSUE TITLE
"The service catalog is empty" Error when project is not set

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#135]
STR:
Create a new OpenStack cloud provider witout a project
deploy an app

result:
2017-01-29 18:00:17,835 [DEBUG]: QS.OpenStack os_session_provider - _do_get_os_session   Getting OpenStack Session:
2017-01-29 18:00:17,835 [DEBUG]: QS.OpenStack os_session_provider - _do_get_os_session   Getting OpenStack Session:
2017-01-29 18:00:17,835 [DEBUG]: QS.OpenStack os_session_provider - _do_get_os_session   OpenStack Resource: controller_url: http://192.168.170.3:5000/v3, domain: default, project_name : , os_user_name : admin
2017-01-29 18:00:17,835 [DEBUG]: QS.OpenStack os_session_provider - _do_get_os_session   OpenStack Resource: controller_url: http://192.168.170.3:5000/v3, domain: default, project_name : , os_user_name : admin
2017-01-29 18:00:17,854 [INFO]: QS.OpenStack openstack_shell - deploy_instance_from_image Deploying: DeployRequest: {"image": {"cloud_provider": "OpenStack", "cp_avail_zone": "", "autoload": true, "instance_flavor": "m1.small", "external_network_uuid": "", "img_uuid": "8da9fa8a-4029-42d3-9f44-229e5ec85ceb", "add_floating_ip": true}, "app_name": "CentOS"}
2017-01-29 18:00:17,855 [INFO]: QS.OpenStack openstack_shell - deploy_instance_from_image Deploying: App: CentOS
2017-01-29 18:00:17,855 [INFO]: QS.OpenStack deploy_operation - deploy               Inside Deploy Operation.
2017-01-29 18:00:17,861 [INFO]: QS.OpenStack openstack_shell - deploy_instance_from_image Deploying: DeployRequest: {"image": {"cloud_provider": "OpenStack", "cp_avail_zone": "", "autoload": true, "instance_flavor": "m1.small", "external_network_uuid": "", "img_uuid": "8da9fa8a-4029-42d3-9f44-229e5ec85ceb", "add_floating_ip": true}, "app_name": "CentOS1"}
2017-01-29 18:00:17,862 [INFO]: QS.OpenStack openstack_shell - deploy_instance_from_image Deploying: App: CentOS1
2017-01-29 18:00:17,862 [INFO]: QS.OpenStack deploy_operation - deploy               Inside Deploy Operation.
2017-01-29 18:00:17,937 [INFO]: QS.OpenStack nova_instance_service - create_instance      Creating OpenStack Instance for Image: 8da9fa8a-4029-42d3-9f44-229e5ec85ceb, Flavor: m1.small
2017-01-29 18:00:17,937 [INFO]: QS.OpenStack nova_instance_service - create_instance      Creating OpenStack Instance for Image: 8da9fa8a-4029-42d3-9f44-229e5ec85ceb, Flavor: m1.small
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__             Error occurred: Traceback (most recent call last):
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\cloudshell\cp\openstack\openstack_shell.py", line 151, in deploy_instance_from_image
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 logger=logger)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\cloudshell\cp\openstack\command\operations\deploy_operation.py", line 35, in deploy
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 logger=logger)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\cloudshell\cp\openstack\domain\services\nova\nova_instance_service.py", line 43, in create_instance
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 img_obj = client.images.find(id=deploy_req_model.img_uuid)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\base.py", line 391, in find
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 matches = self.findall(**kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\base.py", line 447, in findall
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 listing = self.list(**list_kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\v2\images.py", line 87, in list
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return self._list('/images%s%s' % (detail, query), 'images')
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\base.py", line 249, in _list
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 resp, body = self.api.client.get(url)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\adapter.py", line 217, in get
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return self.request(url, 'GET', **kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\client.py", line 107, in request
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 **kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\adapter.py", line 374, in request
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\adapter.py", line 142, in request
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return self.session.request(url, method, **kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\wrapt\wrappers.py", line 561, in __call__
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 args, kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\positional\__init__.py", line 101, in inner
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return wrapped(*args, **kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\session.py", line 513, in request
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 **endpoint_filter)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\session.py", line 856, in get_endpoint
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return auth.get_endpoint(self, **kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\identity\base.py", line 216, in get_endpoint
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 service_name=service_name)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\wrapt\wrappers.py", line 561, in __call__
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 args, kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\positional\__init__.py", line 101, in inner
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return wrapped(*args, **kwargs)
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\access\service_catalog.py", line 190, in url_for
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__                 raise exceptions.EmptyCatalog('The service catalog is empty.')
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__             EmptyCatalog: The service catalog is empty.
2017-01-29 18:00:17,980 [ERROR]: QS.OpenStack error_handling_context - __exit__             
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__             Error occurred: Traceback (most recent call last):
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\cloudshell\cp\openstack\openstack_shell.py", line 151, in deploy_instance_from_image
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 logger=logger)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\cloudshell\cp\openstack\command\operations\deploy_operation.py", line 35, in deploy
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 logger=logger)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\cloudshell\cp\openstack\domain\services\nova\nova_instance_service.py", line 43, in create_instance
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 img_obj = client.images.find(id=deploy_req_model.img_uuid)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\base.py", line 391, in find
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 matches = self.findall(**kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\base.py", line 447, in findall
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 listing = self.list(**list_kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\v2\images.py", line 87, in list
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return self._list('/images%s%s' % (detail, query), 'images')
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\base.py", line 249, in _list
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 resp, body = self.api.client.get(url)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\adapter.py", line 217, in get
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return self.request(url, 'GET', **kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\novaclient\client.py", line 107, in request
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 **kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\adapter.py", line 374, in request
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\adapter.py", line 142, in request
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return self.session.request(url, method, **kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\wrapt\wrappers.py", line 561, in __call__
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 args, kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\positional\__init__.py", line 101, in inner
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return wrapped(*args, **kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\session.py", line 513, in request
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 **endpoint_filter)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\session.py", line 856, in get_endpoint
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return auth.get_endpoint(self, **kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\identity\base.py", line 216, in get_endpoint
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 service_name=service_name)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\wrapt\wrappers.py", line 561, in __call__
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 args, kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\positional\__init__.py", line 101, in inner
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return wrapped(*args, **kwargs)
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_2_11\lib\site-packages\keystoneauth1\access\service_catalog.py", line 190, in url_for
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__                 raise exceptions.EmptyCatalog('The service catalog is empty.')
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__             EmptyCatalog: The service catalog is empty.
2017-01-29 18:00:18,266 [ERROR]: QS.OpenStack error_handling_context - __exit__

**Comment by gabhijit-izel** [comment]
Probably related to #136 - Please check again with latest driver from Develop.

**Comment by yairbb** [comment]
now there is no option to Create new OpenStack cloud provider without a project.
close this bug.

**Comment by TomerAdmon** [comment]
I think we should protection in the app deployment level for it, not only on the autoload level...
can you reopen?  this is low priority

**Comment by yairbb** [comment]
ok.
