### ISSUE TITLE
connectivity fails with 30+ vms

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#95]

**Comment by TomerAdmon** [comment]
@gabhijit-izel  - Please add content and logs when possible.

**Comment by gabhijit-izel** [comment]
Fixed this on IL setup. This was mainly due to Quotas again - increased network quotas and port quotas and fixed/floating IP quotas for the project Fixed

**Comment by gabhijit-izel** [comment]
![32_instances_10_networks](https://cloud.githubusercontent.com/assets/17586985/22176066/e07f7fd0-e027-11e6-8a00-05e23bd58c12.png)

**Comment by alexazarh** [comment]
Great!
Where do you change this quotas?
Can we show in the error message that it fails due to a quota?

Best regards,
Alex Azarh

**Comment by gabhijit-izel** [comment]
Maximum number of ports exceeded errors 

```
2017-01-21 20:34:04,714 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:04,714 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-aae85bb1-a942-4428-8723-8d15e1256824) during interface attach
2017-01-21 20:34:06,414 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:06,414 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-9fde4d03-5c79-4081-b8c3-6bed98e958e2) during interface attach
2017-01-21 20:34:06,642 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     reserved CIDRs: 192.168.0.0/16,172.16.0.0/16
2017-01-21 20:34:06,642 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     Possible Prefixes that can be used: ['10', '172', '192.168']
2017-01-21 20:34:06,851 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     Allocated Subnets: 10.0.10.0/24,10.0.10.0/24,10.0.2.0/24,10.0.5.0/24,10.0.6.0/24,10.0.7.0/24,10.0.8.0/24,10.0.9.0/24
2017-01-21 20:34:06,851 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     Found 10.0.10.0/24 CIDR
2017-01-21 20:34:08,948 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:08,948 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-a7e3089e-1803-4c32-b77d-81ed85d7472b) during interface attach
2017-01-21 20:34:10,686 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:10,686 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-8f1b1fd8-1b49-4800-a7f4-da5dda371d08) during interface attach
2017-01-21 20:34:12,253 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:12,253 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-24c00f49-bdfa-4de3-9d9b-4c26c903b71d) during interface attach
2017-01-21 20:34:14,243 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:14,243 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-84e8b502-4fa2-40cc-8fcb-1ef7f8057469) during interface attach
2017-01-21 20:34:15,815 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:15,815 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-91cf5b64-13e5-4b4f-8312-3a533273ae1f) during interface attach
2017-01-21 20:34:17,390 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:17,390 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-07b8ed4a-1a7e-41a6-a1ed-1f7c7989622a) during interface attach
2017-01-21 20:34:19,382 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:19,382 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-3487b738-0686-4ab7-b46a-7140827919a5) during interface attach
2017-01-21 20:34:21,076 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:21,076 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-b485bfeb-1ccf-4dab-874b-351fa6c52c19) during interface attach
2017-01-21 20:34:21,381 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     reserved CIDRs: 192.168.0.0/16,172.16.0.0/16
2017-01-21 20:34:21,381 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     Possible Prefixes that can be used: ['10', '172', '192.168']
2017-01-21 20:34:21,588 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     Allocated Subnets: 10.0.10.0/24,10.0.10.0/24,10.0.10.0/24,10.0.2.0/24,10.0.5.0/24,10.0.6.0/24,10.0.7.0/24,10.0.8.0/24,10.0.9.0/24
2017-01-21 20:34:21,588 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     Found 10.0.10.0/24 CIDR
2017-01-21 20:34:23,487 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:23,487 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-1fe92842-7524-466e-9da3-37967024bd62) during interface attach
2017-01-21 20:34:25,046 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:25,046 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-1857075e-d9e7-4bdb-8ba0-266c137fe6fc) during interface attach
2017-01-21 20:34:26,744 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:26,744 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-799a1e48-4072-4e65-8637-f4e8ec16ed1c) during interface attach
2017-01-21 20:34:28,617 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:28,617 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-e0c9171a-18f8-4fe3-a796-237e79633307) during interface attach
2017-01-21 20:34:30,276 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:30,276 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-cb8cb6b4-f429-48de-8901-f9dc78bafba7) during interface attach
2017-01-21 20:34:32,088 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    Exception: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
2017-01-21 20:34:32,088 [INFO]: QS.OpenStack nova_instance_service - attach_nic_to_net    <class 'PortLimitExceeded_Remote'> (HTTP 500) (Request-ID: req-9a8f0528-9531-4175-b6f5-a1e9d9c1c1e2) during interface attach
2017-01-21 20:34:32,523 [DEBUG]: QS.OpenStack neutron_network_service - _get_unused_cidr     reserved CIDRs: 192.168.0.0/16,172.16.0.0/16
```

**Comment by gabhijit-izel** [comment]
Max Servers per server group error (comes only with Affinity Groups) 

```
2017-01-21 19:23:15,088 [INFO]: QS.OpenStack nova_instance_service - create_instance      Creating OpenStack Instance for Image: 2b9904e4-45ed-421d-939e-8ccc362740e2, Flavor: m1.tiny
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__             Error occurred: Traceback (most recent call last):
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\cloudshell\cp\openstack\openstack_shell.py", line 151, in deploy_instance_from_image
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 logger=logger)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\cloudshell\cp\openstack\command\operations\deploy_operation.py", line 35, in deploy
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 logger=logger)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\cloudshell\cp\openstack\domain\services\nova\nova_instance_service.py", line 60, in create_instance
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 instance = client.servers.create(**server_create_args)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\novaclient\v2\servers.py", line 1330, in create
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 **boot_kwargs)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\novaclient\v2\servers.py", line 748, in _boot
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return_raw=return_raw, **kwargs)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\novaclient\base.py", line 340, in _create
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 resp, body = self.api.client.post(url, body=body)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\keystoneauth1\adapter.py", line 223, in post
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 return self.request(url, 'POST', **kwargs)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__               File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_1_13\lib\site-packages\novaclient\client.py", line 117, in request
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__                 raise exceptions.from_response(resp, body, url, method)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__             Forbidden: Quota exceeded, too many servers in group (HTTP 403) (Request-ID: req-827d955b-be43-47f7-88a0-07536d50cb02)
2017-01-21 19:23:17,168 [ERROR]: QS.OpenStack error_handling_context - __exit__             
```

**Comment by gabhijit-izel** [comment]
Fixes for the above two errors -  Quota commands - 

```
neutron quota-update --port 120 --tenant-id   93f93601897c4e07a8f695833a127519

nova quota-update --server-group-members 20 93f93601897c4e07a8f695833a127519
```

In general quotas can be updated using `{nova|neutron} quota-update` command

**Comment by gabhijit-izel** [comment]
@alexazarh - Got following correct error for Quota Exceeded for Server Group Members. So this looks fine.

```
Error: CloudShellAPIError
Description: Command execution failed with error: 'Forbidden'.
Error description: Quota exceeded, too many servers in group (HTTP 403) (Request-ID: req-4da9aab3-32ab-48fb-8a27-4bbf87ac0cd5)
Parameters:
```

**Comment by yairbb** [comment]
![image](https://cloud.githubusercontent.com/assets/20166257/22428633/866f60ba-e710-11e6-9da0-199b89bf9ff4.png)

**Comment by gabhijit-izel** [comment]
Strange - I didn't notice this bug. May be I'd manually changed the timeout to 30mins (don't remember now). Ok. After 118 is merged let's try this.

**Comment by yairbb** [comment]
@gabhijit-izel 
The problem still valid .

error: Exception: Reservation is Active with Errors - General Execution: Queued command expired due to time-to-live timeout.

**Comment by yairbb** [comment]
Logs:
[DisPro.txt](https://github.com/QualiSystems/OpenStack-Shell/files/754613/DisPro.txt)
[TeamServer.Service.txt](https://github.com/QualiSystems/OpenStack-Shell/files/754614/TeamServer.Service.txt)
[QsRuntimeService.txt](https://github.com/QualiSystems/OpenStack-Shell/files/754617/QsRuntimeService.txt)

**Comment by yairbb** [comment]
fixed!
